### PR TITLE
Allow for running initialization scripts

### PR DESCRIPTION
**Pull request by shanegenschaw**
Applies to mssql-server-linux, issue #11, adding functionality to mount initialization scripts and execute them when the container is started.

When a container is started for the first time, it will execute any files with extensions .sh or .sql that are found in /docker-entrypoint-initdb.d. Files will be executed in alphabetical order. You can easily populate your SQL Server services by mounting scripts into that directory and provide custom images with contributed data.

### CODE REVIEW

**Comment by shanegenschaw** [comment]
Looks like this may also help resolve issue #2 and #49

**Comment by twright-msft** [comment]
@shanegenschaw - Thanks for submitting this PR.  Our plan is to add this functionality to a hopefully near future release of SQL Server.  The current thinking is that we would have the sqlservr process execute these SQL scripts on startup as opposed to a .sh with sqlcmd.  That way we can have a universal solution for SQL on Linux and on Windows.  The sqlservr process could look for an env variable which contained either a directory path to a set of files or a json formatted list of full paths to files.  What do you think about that approach?

**Comment by shanegenschaw** [comment]
@twright-msft - your approach sounds fantastic. Good idea to have a universal & consistent solution across platforms. Thanks for your consideration!

**Comment by twright-msft** [comment]
OK cool.  We'll get 'er done then.  We'll close out this PR since it will be implemented in a different but conceptually similar way.  Thanks for contributing and keep the suggestions/PRs coming!

**Comment by kspearrin** [comment]
@twright-msft Was this ever done? Not able to find any docs about it. For now I'm trying to run an `entrypoint.sh` but that doesn't work since you have to call `/opt/mssql/bin/sqlservr` first to start up sql server and that never returns. ex:

```
#!/bin/sh

/opt/mssql/bin/sqlservr
# the above never returns so the script below doesn't get run... :(
/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -i /setup.sql
```

**Comment by twright-msft** [comment]
Take a look at this example:
https://github.com/twright-msft/mssql-node-docker-demo-app

**Comment by manish-panwar** [comment]
Any luck on having a better solution?

**Comment by potatoqualitee** [comment]
> Our plan is to add this functionality to a hopefully near future release of SQL Server. 

Any chance this can be in 2022? 😊

**Comment by tracker1** [comment]
Something to look at...

https://github.com/tracker1/mssql-docker-enhanced

**Comment by potatoqualitee** [comment]
Thank you but I am looking for official Microsoft support

**Comment by jrichardsz** [comment]
Mysql, MariaDb, Postgress, even Oracle has the classic

```
    volumes:
     - ./my/database:/docker-entrypoint-initdb.d 
```

@shanegenschaw your approach was good. No body uses windows for docker :(

**Comment by srstsavage** [comment]
+1, it's been five years, let's be realistic and not let the perfect be the enemy of the good. Can this please get re-opened and merged?

**Comment by davidmpaz** [comment]
Hi @twright-msft,

regarding your statement:

> OK cool. We'll get 'er done then. We'll close out this PR since it will be implemented in a different but conceptually similar way. Thanks for contributing and keep the suggestions/PRs coming!

Is this still the case? Can the community expect any outcome in this direction?

Thanks in advance,
David

**Comment by potatoqualitee** [comment]
> > Our plan is to add this functionality to a hopefully near future release of SQL Server.
> 
> Any chance this can be in 2022? 😊

Any chance this can be in 2025? 😊

**Pull request closed without merging**
