### PR TITLE
Fixes for StatefulSet deployment. Add questions.yml and app-readme.md for rancher chart

### PR DESCRIPTION
**Pull request by jamesongithub**

### CODE REVIEW

**Comment by jamesongithub** [comment]
@amvin87 first pass for rancher chart

**Comment by anubisg1** [comment]
i would also add the possibility to have extra volumes and extravolumemounts to allow the SA_PASSWORD to be injected as a secret pulled from a vault 

to values.yaml add

```
extraVolumes: []

extraVolumeMounts: []
```

to deployment.yaml add:

```
          volumeMounts:
           - name: mssql
             mountPath: "/var/opt/mssql"
           - name: mssql-config-volume
             mountPath: /var/opt/config
           {{- if .Values.extraVolumeMounts }}
           {{- toYaml .Values.extraVolumeMounts | nindent 11 }}
           {{- end }}
      volumes:
      - name: mssql-config-volume
        configMap:
         name: mssql
      {{- if .Values.extraVolumes }}
      {{- toYaml .Values.extraVolumes | nindent 6 }}
      {{- end }}
```

**Comment by jamesongithub** [comment]
> i would also add the possibility to have extra volumes and extravolumemounts to allow the SA_PASSWORD to be injected as a secret pulled from a vault
> 
> to values.yaml add
> 
> ```
> extraVolumes: []
> 
> extraVolumeMounts: []
> ```
> 
> to deployment.yaml add:
> 
> ```
>           volumeMounts:
>            - name: mssql
>              mountPath: "/var/opt/mssql"
>            - name: mssql-config-volume
>              mountPath: /var/opt/config
>            {{- if .Values.extraVolumeMounts }}
>            {{- toYaml .Values.extraVolumeMounts | nindent 11 }}
>            {{- end }}
>       volumes:
>       - name: mssql-config-volume
>         configMap:
>          name: mssql
>       {{- if .Values.extraVolumes }}
>       {{- toYaml .Values.extraVolumes | nindent 6 }}
>       {{- end }}
> ```

maybe in the next pr. is this w/ hashicorp vault?

**Comment by anubisg1** [comment]
extraVoumes/Mounts can be used for many things, but in the usecase i was thinking about it's related to Azure Keyvault 

the setup would look like this.

values.yml

```
extraVolumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-vault"

extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
    readOnly: true
```

vault-providerclass.yml (obviously i removed sensitive information from below)

```
piVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-vault
spec:
  provider: azure
  secretObjects:
  - secretName: mssql
    type: Opaque
    data:
      - key: SA_PASSWORD
        objectName: mssql-password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "IDENTITY_ID"
    keyvaultName: DevKbnVault
    objects: |
      array:
        - |
          objectName: mssql-password
          objectType: secret
    tenantId: TENANT_ID
```

**Review by amvin87 — APPROVED** [review]

**Pull request merged**
