### PR TITLE
rhel7 & centos mods, makefile additions

### PR DESCRIPTION
**Pull request by tchughesiv**
TO-DO -> populate the RHEL help.md file and it's Dockerfile labels accordingly.

### CODE REVIEW

**Comment by tchughesiv** [comment]
fwiw... its not in this PR because it appears code changes may be required but i'd like to eventually support running the centos/rhel images w/ an arbitrary uid... something openshift does by default.
today however, if appears sqlservr may be checking for uid 0 at runtime? e.g.
```shell
$ id
uid=1000014406(root) gid=0(root) groups=0(root)

$ sqlservr 
Aborted
```

again, this is for another PR, another day... but we'd like to start the conversation.

**Comment by tchughesiv** [comment]
I've gone ahead and split out CentOS into its own directory.

**Comment by twright-msft** [comment]
Thanks @tchughesiv ! :)

**Comment by tchughesiv** [comment]
@twright-msft 
fwiw... 
_the following is not in this PR because it appears code changes may be required_
i'd like to eventually support running the centos/rhel images w/ an arbitrary uid... something openshift does by default.
today however, if appears sqlservr may be checking for uid 0 at runtime? e.g.
```shell
# docker run -u 1000014406 -e ACCEPT_EULA=Y -e SA_PASSWORD=yourStrong@Password -p 1433:1433 -d microsoft/mssql-server-linux

$ id
uid=1000014406(root) gid=0(root) groups=0(root)

$ sqlservr 
Aborted
```

again, this is for another PR, another day... but we'd like to start the conversation.

**Pull request merged**
